### ISSUE TITLE
Mixin apply error (server crash)

### ISSUE THREAD

**Issue by srnyx** [KyotoHimself/LogIPRemover#1]
**Mod loader:** Fabric
**Loader version:** 0.14.19
**MC Version:** 1.19.4
**`latest.log`:** https://paste.srnyx.xyz/azixatogur.yaml

**Comment by KyotoHimself** [comment]
Heya, I just released a new version of the mod which hopefully fixes things. Give it a try and lmk if it works.

**Comment by srnyx** [comment]
> Heya, I just released a new version of the mod which hopefully fixes things. Give it a try and lmk if it works.

Still crashing, same error

**Comment by KyotoHimself** [comment]
Heya, sorry for taking so long to fix this but version 1.0.2 should finally fix things.

**Comment by srnyx** [comment]
Yep, it works, thank you!
